// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mikejwhitehead/jukebox/ent/card"
	"github.com/mikejwhitehead/jukebox/ent/cardscan"
	"github.com/mikejwhitehead/jukebox/ent/playlist"
	"github.com/mikejwhitehead/jukebox/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	cardFields := schema.Card{}.Fields()
	_ = cardFields
	// cardDescCreated is the schema descriptor for created field.
	cardDescCreated := cardFields[1].Descriptor()
	// card.DefaultCreated holds the default value on creation for the created field.
	card.DefaultCreated = cardDescCreated.Default.(func() time.Time)
	// cardDescModified is the schema descriptor for modified field.
	cardDescModified := cardFields[2].Descriptor()
	// card.DefaultModified holds the default value on creation for the modified field.
	card.DefaultModified = cardDescModified.Default.(func() time.Time)
	// card.UpdateDefaultModified holds the default value on update for the modified field.
	card.UpdateDefaultModified = cardDescModified.UpdateDefault.(func() time.Time)
	cardscanFields := schema.CardScan{}.Fields()
	_ = cardscanFields
	// cardscanDescScanAt is the schema descriptor for scan_at field.
	cardscanDescScanAt := cardscanFields[0].Descriptor()
	// cardscan.DefaultScanAt holds the default value on creation for the scan_at field.
	cardscan.DefaultScanAt = cardscanDescScanAt.Default.(func() time.Time)
	playlistFields := schema.Playlist{}.Fields()
	_ = playlistFields
	// playlistDescCreated is the schema descriptor for created field.
	playlistDescCreated := playlistFields[1].Descriptor()
	// playlist.DefaultCreated holds the default value on creation for the created field.
	playlist.DefaultCreated = playlistDescCreated.Default.(func() time.Time)
	// playlistDescModified is the schema descriptor for modified field.
	playlistDescModified := playlistFields[2].Descriptor()
	// playlist.DefaultModified holds the default value on creation for the modified field.
	playlist.DefaultModified = playlistDescModified.Default.(func() time.Time)
	// playlist.UpdateDefaultModified holds the default value on update for the modified field.
	playlist.UpdateDefaultModified = playlistDescModified.UpdateDefault.(func() time.Time)
}
