// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// CardScan is the predicate function for cardscan builders.
type CardScan func(*sql.Selector)

// Playlist is the predicate function for playlist builders.
type Playlist func(*sql.Selector)
